#!/usr/bin/env python3
"""Derive ARPAbet -> eSpeak-IPA empirically, and print a table to paste into arpabet.py.

BUILD TOOLING ONLY. Never shipped, never imported at runtime.

WHY NOT HAND-WRITE IT
---------------------
A first attempt used a textbook ARPAbet-to-IPA table and measured 22.4% word
error against 6.0% for ghost's own formant synthesizer - a neural model losing
to a Klatt synth, which is not a thing that happens unless the input is wrong.
The errors were systematic ("lamp" heard as "dollop", "cold" as "full").

The cause: the symbols in a Piper voice's `phoneme_id_map` are eSpeak-NG's own
IPA output for that language, which is not textbook IPA. eSpeak writes length
marks and its own rhotics - `ɹˈuːm` not `ɹum`, `θˈɜːɾi` not `θɚti` - and those
choices are dialect- and version-specific. Guessing them is how you get a model
that mispronounces confidently.

So: ask eSpeak directly, once, and commit the answer.

THE LICENSING POINT, which is the whole reason this is a separate script
-----------------------------------------------------------------------
eSpeak-NG is GPLv3. Running it HERE, at build time, to produce a static lookup
table keeps the GPL in tooling: the shipped artifact contains a dict literal,
which is data, and ghost's runtime never imports, links or invokes eSpeak. That
is the same discipline as generating a lookup table from any GPL reference work.

    pip install espeakng-loader phonemizer     # build venv only
    python build_arpabet_map.py
"""

from __future__ import annotations

# One probe word per ARPAbet phone, with the phone's position, so the symbol can
# be read off unambiguously. These are the conventional CMU example words.
PROBES: list[tuple[str, str, str]] = [
    # (ARPAbet, word, the rest of the word's phones, for stripping)
    ("AA", "odd", "d"), ("AE", "at", "t"), ("AH", "hut", "h|t"),
    ("AO", "ought", "t"), ("AW", "cow", "k"), ("AY", "hide", "h|d"),
    ("EH", "ed", "d"), ("ER", "hurt", "h|t"), ("EY", "ate", "t"),
    ("IH", "it", "t"), ("IY", "eat", "t"), ("OW", "oat", "t"),
    ("OY", "toy", "t"), ("UH", "hood", "h|d"), ("UW", "two", "t"),
    ("B", "be", ""), ("CH", "cheese", ""), ("D", "dee", ""),
    ("DH", "thee", ""), ("F", "fee", ""), ("G", "green", ""),
    ("HH", "he", ""), ("JH", "gee", ""), ("K", "key", ""),
    ("L", "lee", ""), ("M", "me", ""), ("N", "knee", ""),
    ("NG", "ping", ""), ("P", "pee", ""), ("R", "read", ""),
    ("S", "sea", ""), ("SH", "she", ""), ("T", "tea", ""),
    ("TH", "theta", ""), ("V", "vee", ""), ("W", "we", ""),
    ("Y", "yield", ""), ("Z", "zee", ""), ("ZH", "seizure", ""),
]

STRESS_MARKS = "ˈˌ"


def espeak(word: str) -> str:
    import espeakng_loader
    from phonemizer.backend.espeak.wrapper import EspeakWrapper
    EspeakWrapper.set_library(espeakng_loader.get_library_path())
    EspeakWrapper.set_data_path(espeakng_loader.get_data_path())
    from phonemizer import phonemize
    out = phonemize([word], language="en-us", backend="espeak",
                    strip=True, with_stress=True)[0]
    return "".join(c for c in out if c not in STRESS_MARKS)


def main() -> int:
    print("# ARPAbet -> eSpeak-NG en-us IPA, generated by build_arpabet_map.py.")
    print("# Do not hand-edit: regenerate instead. See that script for why.")
    print("ARPA_TO_IPA = {")
    for arpa, word, _ in PROBES:
        ipa = espeak(word)
        print('    %-6s %-14s # %s' % ('"%s":' % arpa, '"%s",' % ipa, word))
    print("}")
    print()
    print("# Sanity probes - these must round-trip correctly:")
    for w in ["lamp", "cold", "room", "thirty", "candle", "house", "slowly"]:
        print("#   %-9s %s" % (w, espeak(w)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
