"""The paper's standing conjectures, collected in one place.

Each conjecture is one short YAML file in this package's directory - a single
falsifiable sentence (optionally named, optionally cited), discussed in full
wherever it arises in the paper. The exporter concatenates them, ordered, into a
``\\paperConjectures`` macro that ``main.tex`` drops into the Discussion. New
conjectures are added by dropping a file here; no LaTeX edit needed.

A conjecture file::

    tag: Lottery engineering        # optional short lead-in (bolded)
    order: 30                       # sort key (default 100)
    cite: [frankle2019lottery]      # optional bibkeys -> \\cite{...}
    claim: >                        # the one falsifiable sentence
      The reachability of good sparse subnetworks is set by the prior ...
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List

import yaml

CONJECTURES_DIR = Path(__file__).parent
# praxis/pillars/conjectures/__init__.py -> repo root is parents[3].
RESEARCH_DIR = Path(__file__).parents[3] / "research"
OUT_PATH = RESEARCH_DIR / "conjectures.tex"


@dataclass(frozen=True)
class Conjecture:
    """One falsifiable one-liner, loaded from a conjectures/*.yml file."""

    id: str
    claim: str
    tag: str = ""
    cite: List[str] = field(default_factory=list)
    order: int = 100


def _one_line(text: str) -> str:
    """Folded-scalar prose -> a single line (a conjecture is one sentence)."""
    return re.sub(r"\s+", " ", (text or "").strip())


def _load(path: Path) -> Conjecture:
    raw = yaml.safe_load(path.read_text()) or {}
    if "claim" not in raw:
        raise ValueError(f"{path.name}: conjecture must define 'claim'")
    cite = raw.get("cite") or []
    return Conjecture(
        id=path.stem,
        claim=_one_line(raw["claim"]),
        tag=str(raw.get("tag", "")).strip(),
        cite=list(cite) if isinstance(cite, list) else [cite],
        order=raw.get("order", 100),
    )


def load_conjectures() -> Dict[str, Conjecture]:
    """All conjectures from this directory, keyed by id (filename stem)."""
    return {p.stem: _load(p) for p in sorted(CONJECTURES_DIR.glob("*.yml"))}


CONJECTURES: Dict[str, Conjecture] = load_conjectures()


def _render_item(c: Conjecture) -> str:
    lead = f"\\textbf{{{c.tag}.}} " if c.tag else ""
    cite = f"~\\cite{{{','.join(c.cite)}}}" if c.cite else ""
    return f"  \\item {lead}{c.claim}{cite}"


def render(conjectures: Dict[str, Conjecture]) -> str:
    """The ``\\paperConjectures`` macro body (empty if no conjectures)."""
    ordered = sorted(conjectures.values(), key=lambda c: (c.order, c.id))
    if not ordered:
        return (
            "% Generated by praxis/pillars/conjectures - do not edit by hand.\n"
            "\\newcommand{\\paperConjectures}{}\n"
        )
    items = "\n".join(_render_item(c) for c in ordered)
    return (
        "% Generated by praxis/pillars/conjectures - do not edit by hand.\n"
        "\\newcommand{\\paperConjectures}{%\n"
        "\\subsection{Standing conjectures}\n"
        "We gather the paper's falsifiable conjectures in one place; each is "
        "discussed where it arises. They are bets about reachability and cost, "
        "not theorems, and each names what would refute it.\n"
        "\\begin{itemize}\n"
        f"{items}\n"
        "\\end{itemize}\n}\n"
    )


def export_conjectures() -> Dict:
    """Write research/conjectures.tex. Returns a summary dict."""
    os.makedirs(RESEARCH_DIR, exist_ok=True)
    OUT_PATH.write_text(render(CONJECTURES))
    return {"count": len(CONJECTURES), "ids": sorted(CONJECTURES)}
