extends RefCounted
class_name WallpaperGroup

## WallpaperGroup - the seventeen plane symmetry groups, as a table plus an enumerator.
##
## A wallpaper group is the complete answer to "in how many genuinely different ways can
## one motif tile the plane" - the classification is finite and it is seventeen. Every
## repeating pattern that has ever been printed, woven or tiled is one of these, and what
## separates them is not the motif at all but the LATTICE it repeats on and the point-group
## operations (rotations, mirrors, glides) that sit inside one cell. So the right shape for
## the primitive is a table, not a family of hand-written drawing routines: a group is a
## lattice kind plus a handful of GENERATORS, and everything else - the full set of copies,
## which of them are mirrored, where the cells fall on screen - is derived.
##
## THE REPRESENTATION. Every operation is written in FRACTIONAL lattice coordinates, where
## the point (u, v) means u*a1 + v*a2. That is the crystallographer's convention and it is
## the reason this table is exact: in fractional coordinates every point-group operation of
## every plane group has INTEGER matrix entries and translation parts that are exact halves,
## whatever the lattice's real angle or aspect. A 120-degree rotation is [[0,-1],[1,-1]] -
## no trigonometry, no drift, no epsilon comparisons. Cartesian transforms are recovered at
## the end by conjugating with the basis matrix A = [a1 a2]:  X = A M A^-1.
##
## THE CLOSURE. Only generators are stored, never the full coset list, and the constructor
## closes the group by breadth-first composition modulo the lattice (translation parts taken
## mod 1). Two reasons. It is shorter - p6m is one rotation and one mirror rather than twelve
## matrices to typo - and, more importantly, it CANNOT produce an inconsistent group: whatever
## generators are listed, the result is closed under composition by construction, so the
## pattern always maps onto itself exactly. That matters here because a wallpaper pattern with
## a nearly-right symmetry looks worse than one with none; the eye finds the flaw immediately.
## The closure terminates because integer matrices compose to integer matrices and halves
## compose to halves, so the element set is bounded (order 12 point group x 4 centrings at
## worst); [constant MAX_COSETS] is a belt-and-braces cap, not the real bound.
##
## GLIDES AND CENTRINGS FALL OUT. pg is one operation - a mirror carrying a half-cell
## translation - and its square reduces to the identity because (0, 1) is a lattice vector.
## The centred lattices (cm, cmm) are not a sixth lattice shape here: they are a rectangular
## lattice plus a coset with identity linear part and translation (1/2, 1/2), which is exactly
## what "centred" means. Both cases need no special code at all, which is the payoff of
## working modulo the lattice.
##
## HANDEDNESS. Reflected cosets are flagged (`flip`), because a reflected copy of a polygon
## comes out with reversed winding. Nothing in ghost's 2D path culls by winding, so this is
## advisory rather than load-bearing today - but a caller that fans a polygon from a point,
## or that ever moves this geometry onto a culled path, wants to know.

## Cap on the closure. The largest real plane group is p6m at order 12, and a centring can
## double a coset count, so 64 is far past anything legitimate - it exists only so a mistyped
## generator can never spin forever.
const MAX_COSETS := 64

## Cap on cells emitted by one [method cell_offsets] call. A caller that has sized its lattice
## badly gets a truncated pattern rather than a frozen frame.
const MAX_CELLS := 1200

## sqrt(3)/2 - the height of the hexagonal lattice's second basis vector.
const HEX_H := 0.8660254037844386

## The seventeen groups. `lattice` names the cell shape the group REQUIRES (a 4-fold rotation
## cannot live on a rectangle, a 3-fold cannot live on a square), and `gens` lists generators
## as [m00, m01, m10, m11, tu, tv] in fractional coordinates: the 2x2 matrix acting on (u, v),
## then a translation in cell fractions.
##
## Reading a few of them: `[-1, 0, 0, -1, 0, 0]` is a half turn. `[-1, 0, 0, 1, 0, 0.5]` is a
## mirror in u composed with half a cell along v - a GLIDE, which is why pg has no mirror lines
## in it despite being generated by a mirror matrix. `[1, 0, 0, 1, 0.5, 0.5]` is the pure
## centring translation that turns pm into cm. The hexagonal matrices look strange only because
## a1 and a2 sit at 120 degrees: there, a 3-fold rotation sends a1 -> a2 and a2 -> -a1-a2.
const GROUPS := {
	"p1":   {"lattice": "oblique", "gens": []},
	"p2":   {"lattice": "oblique", "gens": [[-1, 0, 0, -1, 0.0, 0.0]]},
	"pm":   {"lattice": "rect",    "gens": [[-1, 0, 0, 1, 0.0, 0.0]]},
	"pg":   {"lattice": "rect",    "gens": [[-1, 0, 0, 1, 0.0, 0.5]]},
	"cm":   {"lattice": "rect",    "gens": [[-1, 0, 0, 1, 0.0, 0.0], [1, 0, 0, 1, 0.5, 0.5]]},
	"pmm":  {"lattice": "rect",    "gens": [[-1, 0, 0, 1, 0.0, 0.0], [1, 0, 0, -1, 0.0, 0.0]]},
	"pmg":  {"lattice": "rect",    "gens": [[-1, 0, 0, -1, 0.0, 0.0], [1, 0, 0, -1, 0.5, 0.0]]},
	"pgg":  {"lattice": "rect",    "gens": [[-1, 0, 0, -1, 0.0, 0.0], [1, 0, 0, -1, 0.5, 0.5]]},
	"cmm":  {"lattice": "rect",    "gens": [[-1, 0, 0, 1, 0.0, 0.0], [1, 0, 0, -1, 0.0, 0.0],
			[1, 0, 0, 1, 0.5, 0.5]]},
	"p4":   {"lattice": "square",  "gens": [[0, -1, 1, 0, 0.0, 0.0]]},
	"p4m":  {"lattice": "square",  "gens": [[0, -1, 1, 0, 0.0, 0.0], [-1, 0, 0, 1, 0.0, 0.0]]},
	"p4g":  {"lattice": "square",  "gens": [[0, -1, 1, 0, 0.0, 0.0], [-1, 0, 0, 1, 0.5, 0.5]]},
	"p3":   {"lattice": "hex",     "gens": [[0, -1, 1, -1, 0.0, 0.0]]},
	"p3m1": {"lattice": "hex",     "gens": [[0, -1, 1, -1, 0.0, 0.0], [1, -1, 0, -1, 0.0, 0.0]]},
	"p31m": {"lattice": "hex",     "gens": [[0, -1, 1, -1, 0.0, 0.0], [0, 1, 1, 0, 0.0, 0.0]]},
	"p6":   {"lattice": "hex",     "gens": [[1, -1, 1, 0, 0.0, 0.0]]},
	"p6m":  {"lattice": "hex",     "gens": [[1, -1, 1, 0, 0.0, 0.0], [1, -1, 0, -1, 0.0, 0.0]]},
}

## Which group this is, one of [constant GROUPS].
var name := "p1"
## The cell shape it lives on: "oblique", "rect", "square" or "hex".
var lattice := "oblique"
## The lattice basis, in pixels. Every copy of the pattern sits at i*a1 + j*a2.
var a1 := Vector2(1.0, 0.0)
var a2 := Vector2(0.0, 1.0)
## The point group as CARTESIAN transforms, one per coset: {"xf": Transform2D, "flip": bool}.
## Always contains the identity first. Its size is the group's order.
var cosets: Array = []

var _basis := Transform2D.IDENTITY


## The lattice basis a group would use at the given cell length, before any group is built.
## Exposed because a caller usually has to SIZE the cell (from a target cell count) before it
## can construct anything, and sizing needs the cell's area, which needs the basis.
static func basis_of(kind: String, cell: float, ratio := 1.0, angle_deg := 90.0) -> PackedVector2Array:
	var c := maxf(0.001, cell)
	var r := clampf(ratio, 0.1, 10.0)
	if kind == "square":
		return PackedVector2Array([Vector2(c, 0.0), Vector2(0.0, c)])
	if kind == "rect":
		return PackedVector2Array([Vector2(c, 0.0), Vector2(0.0, c * r)])
	if kind == "hex":
		return PackedVector2Array([Vector2(c, 0.0), Vector2(-0.5 * c, HEX_H * c)])
	var t := deg_to_rad(clampf(angle_deg, 25.0, 155.0))
	return PackedVector2Array([Vector2(c, 0.0), Vector2(cos(t), sin(t)) * c * r])


static func lattice_of(gname: String) -> String:
	var e: Dictionary = GROUPS.get(gname, GROUPS["p1"])
	return String(e["lattice"])


## Area of this group's cell at unit cell length - i.e. |a1 x a2| with cell = 1. Multiply by
## cell*cell for the real area. A caller solving "how long must the cell be for N cells to
## cover this rect" needs exactly this factor, and it depends on the lattice kind (1 for
## square, `ratio` for rectangular, sqrt(3)/2 for hexagonal, ratio*sin(angle) for oblique).
static func unit_cell_area(gname: String, ratio := 1.0, angle_deg := 90.0) -> float:
	var b := basis_of(lattice_of(gname), 1.0, ratio, angle_deg)
	return maxf(0.0001, absf(b[0].cross(b[1])))


## Build a group at a concrete cell size. [param ratio] is the second basis vector's length
## relative to the first (rectangular and oblique lattices only) and [param angle_deg] the
## angle between them (oblique only); both are ignored where the group's symmetry fixes them.
static func make(gname: String, cell: float, ratio := 1.0, angle_deg := 90.0) -> WallpaperGroup:
	var g := WallpaperGroup.new()
	g.name = gname if GROUPS.has(gname) else "p1"
	var e: Dictionary = GROUPS[g.name]
	g.lattice = String(e["lattice"])
	var b := basis_of(g.lattice, cell, ratio, angle_deg)
	g.a1 = b[0]
	g.a2 = b[1]
	g._basis = Transform2D(g.a1, g.a2, Vector2.ZERO)
	g._close(e["gens"])
	return g


## The group's order - how many copies of the motif one cell carries.
func order() -> int:
	return cosets.size()


## A lattice vector by integer coefficients, in pixels. The only translations that leave the
## pattern invariant, which is what makes a glide along one of them read as a STEP rather than
## as drift: at the end of the move the picture is identical.
func lattice_vector(i: int, j: int) -> Vector2:
	return a1 * float(i) + a2 * float(j)


## Every cell origin that can put ink inside the rect [-half, half], as cartesian offsets.
##
## The lattice is walked in fractional coordinates, so the enumeration is exact for a sheared
## cell rather than a square approximation. Mapping the rect's four corners through A^-1 gives
## a fractional bounding box; that box is a strict SUPERSET of what is visible once the lattice
## is oblique (a 50-degree cell overshoots by roughly its own shear), so each candidate is then
## tested against the rect directly. Dropping the invisible ones matters because the caller
## pays one draw call per cell.
##
## [param margin] is how far the motif reaches past its own cell origin - include the glide
## excursion in it, or the pattern will pull a bare edge into frame mid-step.
func cell_offsets(half: Vector2, margin: float) -> PackedVector2Array:
	var out := PackedVector2Array()
	var inv := _basis.affine_inverse()
	var umin := INF
	var umax := -INF
	var vmin := INF
	var vmax := -INF
	var corners := PackedVector2Array([
		Vector2(-half.x, -half.y), Vector2(half.x, -half.y),
		Vector2(half.x, half.y), Vector2(-half.x, half.y)])
	for c in corners:
		var fc: Vector2 = inv * c
		umin = minf(umin, fc.x)
		umax = maxf(umax, fc.x)
		vmin = minf(vmin, fc.y)
		vmax = maxf(vmax, fc.y)
	var pu := int(ceil(margin / maxf(1.0, a1.length()))) + 1
	var pv := int(ceil(margin / maxf(1.0, a2.length()))) + 1
	var i0 := int(floor(umin)) - pu
	var i1 := int(ceil(umax)) + pu
	var j0 := int(floor(vmin)) - pv
	var j1 := int(ceil(vmax)) + pv
	var lx := half.x + margin
	var ly := half.y + margin
	for j in range(j0, j1 + 1):
		for i in range(i0, i1 + 1):
			var off := a1 * float(i) + a2 * float(j)
			if absf(off.x) > lx or absf(off.y) > ly:
				continue
			out.append(off)
			if out.size() >= MAX_CELLS:
				return out
	return out


# Breadth-first closure of the generators modulo the lattice, then conjugation into cartesian
# space. Elements are carried as [m00, m01, m10, m11, tu, tv]; the translation is reduced mod 1
# after every composition, which is what makes the element set finite.
func _close(gens: Array) -> void:
	var identity := PackedFloat32Array([1.0, 0.0, 0.0, 1.0, 0.0, 0.0])
	var elems: Array = [identity]
	var seen := {}
	seen[_key(identity)] = true
	var head := 0
	while head < elems.size() and elems.size() < MAX_COSETS:
		var e: PackedFloat32Array = elems[head]
		head += 1
		for gi in gens.size():
			var g: Array = gens[gi]
			var c := _compose(g, e)
			var k := _key(c)
			if seen.has(k):
				continue
			seen[k] = true
			elems.append(c)
	cosets = []
	var inv := _basis.affine_inverse()
	for i in elems.size():
		var e2: PackedFloat32Array = elems[i]
		# Transform2D takes its basis as COLUMNS: the images of (1,0) and (0,1).
		var m := Transform2D(Vector2(e2[0], e2[2]), Vector2(e2[1], e2[3]), Vector2(e2[4], e2[5]))
		cosets.append({
			"xf": _basis * m * inv,
			"flip": e2[0] * e2[3] - e2[1] * e2[2] < 0.0,
		})


# g composed with e, applying e first: linear part G*E, translation part G*e.t + g.t.
func _compose(g: Array, e: PackedFloat32Array) -> PackedFloat32Array:
	var m0 := float(g[0])
	var m1 := float(g[1])
	var m2 := float(g[2])
	var m3 := float(g[3])
	return PackedFloat32Array([
		m0 * e[0] + m1 * e[2],
		m0 * e[1] + m1 * e[3],
		m2 * e[0] + m3 * e[2],
		m2 * e[1] + m3 * e[3],
		fposmod(m0 * e[4] + m1 * e[5] + float(g[4]), 1.0),
		fposmod(m2 * e[4] + m3 * e[5] + float(g[5]), 1.0),
	])


# Identity of a coset. Matrix entries are integers and translations are exact halves in every
# one of the seventeen groups, so quantizing the translation to twelfths is lossless here and
# still leaves room for a caller that ever adds a third-cell shift.
func _key(e: PackedFloat32Array) -> String:
	return "%d,%d,%d,%d,%d,%d" % [
		int(round(e[0])), int(round(e[1])), int(round(e[2])), int(round(e[3])),
		int(round(e[4] * 12.0)), int(round(e[5] * 12.0))]
