#!/usr/bin/env python3
"""Render the paper's component-gated prose into ``research/framing.tex``.

The paper (``research/main.tex``) is a living document. Some sections only hold
for runs that use a given component - the crystal head, the CALM codec - so they
are declared as gated :class:`~praxis.research.framing.Fragment`s rather than
written inline. This tool figures out which components the run being written up
actually uses and emits only the matching fragments.

How activation is resolved:
- read the newest run's ``build/runs/<hash>/config.json`` (or ``--experiment``),
- pull the experiment name out of its ``command`` (the ``--<stem>`` flag),
- resolve that experiment's ``extends`` chain to a flat config dict,
- keep fragments whose ``requires`` match, grouped per section.

Output: ``research/framing.tex``, defining one ``\\paperFraming<Section>`` macro
per section (the active fragment bodies, in order). ``main.tex`` ``\\input``s it
and drops each macro at the matching anchor; a clean checkout falls back to the
empty ``\\providecommand`` and simply omits the gated sections.

Usage:
    python tools/export_framing.py                 # newest run
    python tools/export_framing.py --experiment calm-a
    python tools/export_framing.py --json
"""

import argparse
import glob
import importlib.util
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNS_DIR = os.path.join(REPO_ROOT, "build", "runs")
EXP_DIR = os.path.join(REPO_ROOT, "experiments")
OUT_PATH = os.path.join(REPO_ROOT, "research", "framing.tex")

# Non-experiment flags (mirror tools/export_runs.py) - skipped when sniffing the
# experiment name out of a run command.
DENY_FLAGS = {
    "reset", "dev", "no-compile", "compile", "profile-memory", "device",
    "max-steps", "batch-size", "debug", "seed", "host", "port",
}


def _load(name, relpath):
    """Import a module straight from its file, bypassing praxis/__init__ (which
    pulls in torch). Both targets import only stdlib + yaml."""
    spec = importlib.util.spec_from_file_location(name, os.path.join(REPO_ROOT, relpath))
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod  # dataclass resolves __module__ via sys.modules
    spec.loader.exec_module(mod)
    return mod

framing = _load("_framing", "praxis/research/framing.py")
experiments = _load("_experiments", "praxis/cli/loaders/experiments.py")


def experiment_stems():
    return {os.path.splitext(os.path.basename(p))[0] for p in glob.glob(os.path.join(EXP_DIR, "*.yml"))}


def experiment_from_command(command, stems):
    """The ``--<stem>`` experiment flag in a run command, else the first
    non-deny flag (mirrors export_runs.experiment_name)."""
    toks = command.split()
    for t in toks:
        if t.startswith("--") and t[2:] in stems:
            return t[2:]
    for t in toks:
        if t.startswith("--") and t[2:] not in DENY_FLAGS:
            return t[2:]
    return None


def newest_run_command():
    """Command string of the most recently created run, or ''."""
    best, best_key = "", ""
    for cfg_path in glob.glob(os.path.join(RUNS_DIR, "*", "config.json")):
        try:
            cfg = json.load(open(cfg_path))
        except (OSError, ValueError):
            continue
        key = cfg.get("created") or str(os.path.getmtime(cfg_path))
        if key > best_key:
            best, best_key = cfg.get("command", ""), key
    return best


def resolve_config(experiment):
    """Flat config dict for an experiment (extends chain resolved)."""
    path = os.path.join(EXP_DIR, f"{experiment}.yml")
    if not os.path.exists(path):
        raise FileNotFoundError(f"no experiment '{experiment}' at {path}")
    return experiments.load_rendered_config(path, experiments_dir=EXP_DIR)


def section_macro(section):
    """Section anchor -> macro name, e.g. 'harmonic' -> '\\paperFramingHarmonic'."""
    camel = "".join(p.capitalize() for p in section.replace("_", "-").split("-"))
    return f"paperFraming{camel}"


def render(config):
    """Build the framing.tex body and a JSON-able summary from a config."""
    active = framing.active_fragments(config)
    sections = {}
    for frag in active:
        sections.setdefault(frag.section, []).append(frag)

    lines = ["% Generated by tools/export_framing.py - do not edit by hand."]
    for section, frags in sorted(sections.items()):
        bodies = "\n\n".join(f.body for f in frags)
        lines.append(f"\\newcommand{{\\{section_macro(section)}}}{{%\n{bodies}\n}}")

    summary = {
        "active": [f.id for f in active],
        "skipped": [fid for fid in framing.FRAMING if fid not in {f.id for f in active}],
        "sections": {s: [f.id for f in fr] for s, fr in sections.items()},
    }
    return "\n".join(lines) + "\n", summary


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--experiment", help="experiment stem to frame (default: newest run)")
    ap.add_argument("--json", action="store_true", help="print summary as JSON")
    args = ap.parse_args()

    stems = experiment_stems()
    experiment = args.experiment
    if experiment is None:
        experiment = experiment_from_command(newest_run_command(), stems)
    if not experiment:
        print("error: could not determine an experiment (none found, pass --experiment)", file=sys.stderr)
        return 1

    config = resolve_config(experiment)
    body, summary = render(config)
    summary["experiment"] = experiment

    with open(OUT_PATH, "w") as fh:
        fh.write(body)

    if args.json:
        print(json.dumps(summary, indent=2))
    else:
        print(f"wrote {os.path.relpath(OUT_PATH, REPO_ROOT)} for '{experiment}'")
        print(f"  active : {', '.join(summary['active']) or '(none)'}")
        print(f"  skipped: {', '.join(summary['skipped']) or '(none)'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
