#!/usr/bin/env python3
"""Resolve the paper's inline edits into ``research/inlines.tex``.

Each edit (see :mod:`praxis.research.inlines`) maps a LaTeX macro to a value
computed from the repository - a run count, a rate, a metric. This tool runs the
providers and writes one ``\\newcommand`` per edit that yields a value; edits
whose provider returns ``None`` are omitted, so ``main.tex``'s
``\\providecommand`` fallback stands and the prose is unchanged.

Output: ``research/inlines.tex`` (generated, not committed). ``main.tex``
``\\input``s it after ``variables.tex`` so the overrides win.

Usage:
    python tools/export_inlines.py
    python tools/export_inlines.py --json
"""

import argparse
import importlib.util
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PATH = os.path.join(REPO_ROOT, "research", "inlines.tex")


def _load(name, relpath):
    """Import a module by file, bypassing praxis/__init__ (which pulls torch).
    The target imports only stdlib + yaml."""
    spec = importlib.util.spec_from_file_location(name, os.path.join(REPO_ROOT, relpath))
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod  # dataclass resolves __module__ via sys.modules
    spec.loader.exec_module(mod)
    return mod


inlines = _load("_inlines", "praxis/research/inlines.py")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", action="store_true", help="print summary as JSON")
    args = ap.parse_args()

    lines = ["% Generated by tools/export_inlines.py - do not edit by hand."]
    resolved, absent = {}, []
    for edit_id, edit in inlines.INLINES.items():
        body = edit.resolve()
        if body is None:
            absent.append(edit_id)
            continue
        resolved[edit_id] = body
        lines.append(f"\\newcommand{{\\{edit.macro}}}{{{body}}}")

    with open(OUT_PATH, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    if args.json:
        print(json.dumps({"resolved": resolved, "absent": absent}, indent=2))
    else:
        print(f"wrote {os.path.relpath(OUT_PATH, REPO_ROOT)}")
        for eid, body in resolved.items():
            print(f"  {eid}: {body}")
        if absent:
            print(f"  absent (fallback kept): {', '.join(absent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
