"""Build the living paper's generated inputs from current repository state.

The paper in ``research/`` ``\\input``s four generated files; this is the one
command that regenerates all of them, the research-side analogue of
``praxis/web/src/build.py``:

- ``variables.tex`` + ``data/run_*.csv`` - recent validation curves (:mod:`runs`)
- ``framing.tex`` - component-gated prose for the current run (:mod:`framing`)
- ``geometries.tex`` + ``figures/`` - Center PCA density figure (:mod:`geometries`)
- ``inlines.tex`` - single-value substitutions (:mod:`inlines`)

Run it, then build the PDF::

    python -m praxis.pillars.build
    (cd research && latexmk -pdf -outdir=build main.tex && cp build/main.pdf .)

Each step is independent and best-effort: a step that finds nothing to render
(no runs yet, no crystal geometry) leaves the paper's fallbacks in place rather
than failing the build.
"""

import argparse
import os
import sys

from praxis.pillars import (
    conjectures,
    evolution,
    framing,
    geometries,
    ghostmax,
    halting,
    inlines,
    proofs,
    runs,
    strands,
)
from praxis.pillars.geometries import RESEARCH_DIR

_AUTHORS_TEX = os.path.join(RESEARCH_DIR, "authors.tex")


def _tex_escape(s: str) -> str:
    for a, b in (("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"), ("_", r"\_")):
        s = s.replace(a, b)
    return s


def _write_authors(authors) -> None:
    """Write the (already-ordered) author list into the paper's \\author block."""
    names = [_tex_escape(a.strip()) for a in authors if a and a.strip()]
    if not names:
        names = ["Ryan J. Brooks"]
    body = " \\and ".join(names)
    with open(_AUTHORS_TEX, "w") as fh:
        fh.write("% Generated by praxis/pillars/build.py - do not edit by hand.\n")
        fh.write("\\newcommand{\\paperAuthors}{" + body + "}\n")


def build_all(
    n=4,
    metric="auto",
    experiment=None,
    limit=4,
    scan=40,
    as_json=False,
    model=None,
    authors=None,
):
    """Regenerate every paper input. Returns a dict of per-step summaries.

    ``model`` is the live training model (passed by PaperBuildCallback) used for
    snapshot figures that need populated forward state, e.g. the prismatic
    bias/variance strands; omitted on a CLI build (those figures stay empty).
    ``authors`` is the already-ordered author list (the PaperBuildCallback
    resolves first-author + the 10%% shuffle once per run); written to the
    paper's \\author block."""
    summary = {}

    if authors:
        _write_authors(authors)
        summary["authors"] = list(authors)

    result = runs.export_once(n, metric)
    if result:
        runs.report(result, as_json)
    else:
        print("runs: no usable validation data yet; kept existing variables.tex")
    summary["runs"] = result

    try:
        summary["framing"] = framing.export_framing(experiment)
        f = summary["framing"]
        print(f"framing: {', '.join(f['active']) or '(none)'} for '{f['experiment']}'")
    except (ValueError, FileNotFoundError) as e:
        print(f"framing: skipped ({e})")
        summary["framing"] = None

    summary["geometries"] = geometries.export_geometries(limit, scan)
    print(f"geometries: {summary['geometries']['count']} panel(s)")

    try:
        summary["strands"] = strands.export_strands(model)
        s = summary["strands"]
        print(
            f"strands: {'rendered 2 arms' if s['rendered'] else 'no prismatic field'}"
        )
    except Exception as e:  # best-effort, never break the paper build
        print(f"strands: skipped ({e})")
        summary["strands"] = None

    try:
        summary["evolution"] = evolution.export_evolution()
        ev = summary["evolution"]
        print(
            f"evolution: {ev['commits']} commits"
            + (f", focus {ev['focus']}" if ev.get("rendered") else " (no history)")
        )
    except Exception as e:  # best-effort, never break the paper build
        print(f"evolution: skipped ({e})")
        summary["evolution"] = None

    summary["halting"] = halting.export_halting()
    h = summary["halting"]
    print(f"halting: {h['run'] or '(no halting data)'}")

    summary["ghostmax"] = ghostmax.export_ghostmax()
    print(
        f"ghostmax: dampening verified (real mass {summary['ghostmax']['min_mass']:.3g}"
        f" -> {summary['ghostmax']['max_mass']:.3g})"
    )

    summary["inlines"] = inlines.export_inlines()
    res = summary["inlines"]["resolved"]
    print(f"inlines: {', '.join(f'{k}={v}' for k, v in res.items()) or '(none)'}")

    summary["conjectures"] = conjectures.export_conjectures()
    print(f"conjectures: {summary['conjectures']['count']} collected")

    # Theorem-prover (consistency check over the framing<->proof wiring).
    report = proofs.check_consistency(framing.FRAMING)
    summary["proofs"] = report
    for err in report["errors"]:
        print(f"proofs ERROR: {err}")
    for warn in report["warnings"]:
        print(f"proofs WARN: {warn}")
    print(
        f"proofs: {len(framing.FRAMING)} framings, {len(proofs.PROOFS)} proofs, "
        f"{len(report['errors'])} error(s), {len(report['warnings'])} unbacked"
    )

    return summary


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--n", type=int, default=4, help="run curves to include (default 4)"
    )
    ap.add_argument("--metric", default="auto", help="metric column, or 'auto'")
    ap.add_argument("--experiment", help="experiment to frame (default: newest run)")
    ap.add_argument(
        "--limit", type=int, default=4, help="max geometry panels (default 4)"
    )
    ap.add_argument("--scan", type=int, default=40, help="runs to scan for geometries")
    ap.add_argument("--json", action="store_true", help="machine-readable run summary")
    args = ap.parse_args()

    build_all(args.n, args.metric, args.experiment, args.limit, args.scan, args.json)
    return 0


if __name__ == "__main__":
    sys.exit(main())
