"""Build the living paper's generated inputs from current repository state.

A thread (praxis/pillars/thread.py, selected by --title) names the master
document and which of the STEPS below run; each step writes a fragment the
master ``\\input``s behind a fallback. This is the one command that
regenerates all of them, the research-side analogue of
``praxis/web/src/build.py``:

- ``variables.tex`` + ``data/run_*.csv`` - recent validation curves (:mod:`runs`)
- ``framing.tex`` - component-gated prose for the current run (:mod:`framing`)
- ``geometries.tex`` + ``figures/`` - Center PCA density figure (:mod:`geometries`)
- ``inlines.tex`` - single-value substitutions (:mod:`inlines`)

Run it, then build the PDF::

    python -m praxis.pillars.build
    (cd research && latexmk -pdf -outdir=build main.tex && cp build/main.pdf .)

Each step is independent and best-effort: a step that finds nothing to render
(no runs yet, no crystal geometry) leaves the paper's fallbacks in place rather
than failing the build.
"""

import argparse
import os
import sys

from praxis.pillars import (
    conjectures,
    datasets,
    evolution,
    framing,
    geometries,
    ghostmax,
    halting,
    inlines,
    proofs,
    runs,
    spectrum,
    strands,
)
from praxis.pillars.geometries import RESEARCH_DIR
from praxis.pillars.thread import THREAD_REGISTRY, resolve_thread, write_thread

_AUTHORS_TEX = os.path.join(RESEARCH_DIR, "authors.tex")
# Bibliography data lives with the pillars; the build renders it into
# research/ (gitignored there - the PDF carries the citations).
_CITATIONS_SRC = os.path.join(os.path.dirname(__file__), "citations.bib")
_CITATIONS_BIB = os.path.join(RESEARCH_DIR, "citations.bib")


def _tex_escape(s: str) -> str:
    for a, b in (("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"), ("_", r"\_")):
        s = s.replace(a, b)
    return s


def _write_authors(authors) -> None:
    """Write the (already-ordered) author list into the paper's \\author block."""
    names = [_tex_escape(a.strip()) for a in authors if a and a.strip()]
    if not names:
        names = ["Ryan J. Brooks"]
    body = " \\and ".join(names)
    with open(_AUTHORS_TEX, "w") as fh:
        fh.write("% Generated by praxis/pillars/build.py - do not edit by hand.\n")
        fh.write("\\newcommand{\\paperAuthors}{" + body + "}\n")


def _step_runs(ctx):
    result = runs.export_once(ctx["n"], ctx["metric"])
    if result:
        runs.report(result, ctx["as_json"])
    else:
        print("runs: no usable validation data yet; kept existing variables.tex")
    return result


def _step_framing(ctx):
    try:
        f = framing.export_framing(ctx["experiment"])
        print(f"framing: {', '.join(f['active']) or '(none)'} for '{f['experiment']}'")
        return f
    except (ValueError, FileNotFoundError) as e:
        print(f"framing: skipped ({e})")
        return None


def _step_geometries(ctx):
    g = geometries.export_geometries(ctx["limit"], ctx["scan"])
    print(f"geometries: {g['count']} panel(s)")
    return g


def _step_spectrum(ctx):
    s = spectrum.export_spectrum(ctx["limit"], ctx["scan"])
    print(f"spectrum: {s['count']} field(s)")
    return s


def _step_strands(ctx):
    try:
        s = strands.export_strands(ctx["model"])
        print(
            f"strands: {'rendered 2 arms' if s['rendered'] else 'no prismatic field'}"
        )
        return s
    except Exception as e:  # best-effort, never break the paper build
        print(f"strands: skipped ({e})")
        return None


def _step_evolution(ctx):
    try:
        ev = evolution.export_evolution()
        print(
            f"evolution: {ev['commits']} commits"
            + (f", focus {ev['focus']}" if ev.get("rendered") else " (no history)")
        )
        return ev
    except Exception as e:  # best-effort, never break the paper build
        print(f"evolution: skipped ({e})")
        return None


def _step_halting(ctx):
    h = halting.export_halting()
    print(f"halting: {h['run'] or '(no halting data)'}")
    return h


def _step_ghostmax(ctx):
    g = ghostmax.export_ghostmax()
    print(
        f"ghostmax: dampening verified (real mass {g['min_mass']:.3g}"
        f" -> {g['max_mass']:.3g})"
    )
    return g


def _step_datasets(ctx):
    try:
        d = datasets.export_datasets(ctx["n"])
        print(f"datasets: {d['rows']} row(s) across {d['experiments']} experiment(s)")
        return d
    except Exception as e:  # best-effort, never break the paper build
        print(f"datasets: skipped ({e})")
        return None


def _step_inlines(ctx):
    i = inlines.export_inlines()
    res = i["resolved"]
    print(f"inlines: {', '.join(f'{k}={v}' for k, v in res.items()) or '(none)'}")
    return i


def _step_conjectures(ctx):
    c = conjectures.export_conjectures()
    print(f"conjectures: {c['count']} collected")
    return c


def _step_proofs(ctx):
    # Theorem-prover (consistency check over the framing<->proof wiring).
    report = proofs.check_consistency(framing.FRAMING)
    for err in report["errors"]:
        print(f"proofs ERROR: {err}")
    for warn in report["warnings"]:
        print(f"proofs WARN: {warn}")
    print(
        f"proofs: {len(framing.FRAMING)} framings, {len(proofs.PROOFS)} proofs, "
        f"{len(report['errors'])} error(s), {len(report['warnings'])} unbacked"
    )
    return report


# Content generators a thread can enable, in build order. Each writes a tex
# fragment (or data files) the thread's master document inputs behind an
# \IfFileExists + \providecommand fallback.
STEPS = {
    "runs": _step_runs,
    "datasets": _step_datasets,
    "framing": _step_framing,
    "geometries": _step_geometries,
    "spectrum": _step_spectrum,
    "strands": _step_strands,
    "evolution": _step_evolution,
    "halting": _step_halting,
    "ghostmax": _step_ghostmax,
    "inlines": _step_inlines,
    "conjectures": _step_conjectures,
    "proofs": _step_proofs,
}


def build_all(
    n=4,
    metric="auto",
    experiment=None,
    limit=4,
    scan=40,
    as_json=False,
    model=None,
    authors=None,
    thread=None,
):
    """Regenerate the selected thread's paper inputs. Returns per-step summaries.

    ``thread`` is a THREAD_REGISTRY key (or Thread) naming the layout - the
    title block, body prose, and which STEPS run; default is the Blind
    Watchmaker paper. ``model`` is the live training model (passed by
    PaperBuildCallback) used for snapshot figures that need populated forward
    state, e.g. the prismatic bias/variance strands; omitted on a CLI build
    (those figures stay empty). ``authors`` is the already-ordered author list
    (the PaperBuildCallback resolves first-author + the 10%% shuffle once per
    run); written to the paper's \\author block."""
    layout = resolve_thread(thread)
    summary = {"thread": write_thread(layout)}

    import shutil

    shutil.copyfile(_CITATIONS_SRC, _CITATIONS_BIB)

    if authors:
        _write_authors(authors)
        summary["authors"] = list(authors)

    ctx = dict(
        n=n,
        metric=metric,
        experiment=experiment,
        limit=limit,
        scan=scan,
        as_json=as_json,
        model=model,
    )
    for name in layout.pillars:
        summary[name] = STEPS[name](ctx)

    return summary


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--n", type=int, default=4, help="run curves to include (default 4)"
    )
    ap.add_argument("--metric", default="auto", help="metric column, or 'auto'")
    ap.add_argument("--experiment", help="experiment to frame (default: newest run)")
    ap.add_argument(
        "--limit", type=int, default=4, help="max geometry panels (default 4)"
    )
    ap.add_argument("--scan", type=int, default=40, help="runs to scan for geometries")
    ap.add_argument("--json", action="store_true", help="machine-readable run summary")
    ap.add_argument(
        "--title",
        default=None,
        choices=sorted(THREAD_REGISTRY),
        help="paper thread (layout) to build; default blind_watchmaker",
    )
    args = ap.parse_args()

    build_all(
        args.n,
        args.metric,
        args.experiment,
        args.limit,
        args.scan,
        args.json,
        thread=args.title,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
