"""Praxis modeling its own evolution: per-subsystem churn over git history.

A living-paper figure built from ``git log --numstat`` - how much each subsystem
changed over the project's history - with strength decayed by distance from HEAD
(the recency kernel the model itself uses, turned on the repo). Honest: real
churn over real commits, the decay shown as a fade of the distant past, not a
distortion of the history.

Output: research/figures/evolution.png + research/evolution.tex
(\\paperEvolutionFigure). Best-effort: no git / no history -> empty macro so the
paper still builds. See next/the_dial.md.
"""

import os
import subprocess
from collections import defaultdict

from praxis.pillars.geometries import FIG_DIR, REPO_ROOT, RESEARCH_DIR

OUT_TEX = os.path.join(RESEARCH_DIR, "evolution.tex")
MAX_COMMITS = 4000  # cap for speed on long histories
N_BINS = 48

# Path prefix -> subsystem label. First match wins; order matters (specific
# before general). Kept coarse (~8 groups) so the stack stays readable.
SUBSYSTEMS = [
    ("praxis/heads", "heads"),
    ("praxis/attention", "attention"),
    ("praxis/encoders", "encoders"),
    ("praxis/losses", "losses"),
    ("praxis/optimizers", "optimizers"),
    ("praxis/policies", "policies"),
    ("praxis/web", "web"),
    ("praxis/pillars", "paper"),
    ("research", "paper"),
    ("praxis", "core"),
]
OTHER = "other"
# Stable color per subsystem (dark-theme palette, distinct hues).
COLORS = {
    "heads": "#e0566f", "attention": "#e08a3c", "encoders": "#e8c84a",
    "losses": "#5fd08a", "optimizers": "#46c2c8", "policies": "#5a8cf0",
    "web": "#9a6ff0", "paper": "#d06fd0", "core": "#8a93a6", OTHER: "#586072",
}


def _subsystem(path: str) -> str:
    for prefix, label in SUBSYSTEMS:
        if path.startswith(prefix):
            return label
    return OTHER


def _commits():
    """[(unix_ts, {subsystem: churn})] oldest-first, or [] if git is unusable."""
    try:
        out = subprocess.run(
            ["git", "log", f"-n{MAX_COMMITS}", "--no-merges", "--numstat",
             "--date=unix", "--pretty=format:__C__ %at"],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=60, check=False,
        ).stdout
    except Exception:
        return []
    commits, ts, churn = [], None, defaultdict(float)
    for line in out.splitlines():
        if line.startswith("__C__ "):
            if ts is not None:
                commits.append((ts, churn))
            ts, churn = int(line[6:].strip() or 0), defaultdict(float)
        elif "\t" in line:
            ins, dele, path = (line.split("\t", 2) + ["", "", ""])[:3]
            # binary files report "-"; skip them (no line churn).
            if ins == "-" or not path:
                continue
            churn[_subsystem(path)] += float(ins or 0) + float(dele or 0)
    if ts is not None:
        commits.append((ts, churn))
    commits.reverse()  # oldest-first
    return commits


def evolution_data() -> dict:
    """Shared, JSON-serializable evolution signal: per-subsystem line churn over
    ``N_BINS`` time bins (oldest -> HEAD), the colors, and the recency-weighted
    focus ranking. The single source for BOTH output formats - the LaTeX figure
    (matplotlib, below) and the web card (/api/evolution -> canvas). Renderers
    own only presentation (recency fade, fonts); the numbers live here.
    Returns ``None`` when git history is unusable."""
    commits = _commits()
    if len(commits) < 3:
        return None

    t0, t1 = commits[0][0], commits[-1][0]
    span = max(t1 - t0, 1)
    labels = list(dict.fromkeys([lbl for _, lbl in SUBSYSTEMS] + [OTHER]))
    series = {lbl: [0.0] * N_BINS for lbl in labels}
    for ts, churn in commits:
        b = min(int((ts - t0) / span * (N_BINS - 1)), N_BINS - 1)
        for lbl, v in churn.items():
            series.setdefault(lbl, [0.0] * N_BINS)[b] += v

    present = [l for l in labels if sum(series[l]) > 0]
    # Recency-weighted churn (linear decay: newest bin weight 1, oldest ~0).
    w = [i / (N_BINS - 1) for i in range(N_BINS)]
    focus = sorted(
        present, key=lambda l: sum(c * wi for c, wi in zip(series[l], w)), reverse=True
    )
    return {
        "bins": N_BINS,
        "subsystems": present,
        "series": {l: series[l] for l in present},
        "colors": {l: COLORS.get(l, "#586072") for l in present},
        "n_commits": len(commits),
        "focus": focus[:3],
        "x_labels": ["first commit", "now"],
    }


def export_evolution() -> dict:
    data = evolution_data()
    if data is None:
        with open(OUT_TEX, "w") as fh:
            fh.write(
                "% Generated by praxis/pillars/evolution.py - no git history.\n"
                "\\newcommand{\\paperEvolutionFigure}{}\n"
            )
        return {"rendered": False, "commits": 0}

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    present = data["subsystems"]
    series = {l: np.asarray(v) for l, v in data["series"].items()}
    x = np.linspace(0, 1, data["bins"])  # 0 = oldest, 1 = HEAD

    fig, ax = plt.subplots(figsize=(6.4, 3.0), facecolor="#0f1117")
    ax.set_facecolor("#0f1117")
    ax.stackplot(x, *[series[l] for l in present],
                 labels=present, colors=[COLORS.get(l, "#586072") for l in present],
                 linewidth=0)
    # Recency decay: fade the distant past. A black overlay whose opacity falls
    # from the oldest bin to HEAD - "strength decayed by distance from current".
    grad = np.linspace(0.72, 0.0, 256).reshape(1, -1)
    ax.imshow(grad, extent=[0, 1, 0, ax.get_ylim()[1]], aspect="auto",
              cmap=_fade_cmap(), zorder=5, alpha=1.0)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, ax.get_ylim()[1])
    ax.set_xticks([0, 1])
    ax.set_xticklabels(["first commit", "now"], color="#9aa3b2", fontsize=8)
    ax.set_yticks([])
    ax.set_title("Praxis evolving: subsystem churn over its own history",
                 color="#e6e9f0", fontsize=10, fontweight="bold", pad=10)
    leg = ax.legend(loc="upper left", fontsize=6.5, ncol=2, framealpha=0.0,
                    labelcolor="#cfd3dc")
    for txt in leg.get_texts():
        txt.set_color("#cfd3dc")
    fig.tight_layout()
    os.makedirs(FIG_DIR, exist_ok=True)
    out = os.path.join(FIG_DIR, "evolution.png")
    fig.savefig(out, dpi=130, bbox_inches="tight", facecolor="#0f1117")
    plt.close(fig)
    rel = os.path.relpath(out, RESEARCH_DIR)

    focus = data["focus"]
    caption = (
        f"Per-subsystem line churn across the last {data['n_commits']} commits of "
        "Praxis's git history, binned over time (left = first commit, right = "
        "now). The distant past fades: strength is decayed by distance from HEAD "
        "- the same recency kernel the model applies to a sequence, turned on the "
        "repository. By recency-weighted churn the current center of gravity is "
        f"{', '.join(focus[:3])}. The framework charts the hand that builds it."
    )
    with open(OUT_TEX, "w") as fh:
        fh.write("% Generated by praxis/pillars/evolution.py - do not edit by hand.\n")
        fh.write(
            "\\newcommand{\\paperEvolutionFigure}{%\n"
            "\\begin{figure}[tbp]\n  \\centering\n  "
            f"\\includegraphics[width=0.9\\linewidth]{{{rel}}}\n"
            f"  \\caption{{{caption}}}\n"
            "  \\label{fig:evolution}\n"
            "\\end{figure}\n}\n"
        )
    return {"rendered": True, "commits": data["n_commits"], "focus": focus, "path": rel}


def _fade_cmap():
    """Transparent -> dark-bg colormap for the recency fade overlay."""
    from matplotlib.colors import LinearSegmentedColormap

    return LinearSegmentedColormap.from_list(
        "fade", [(0, 0, 0, 0), (0.059, 0.067, 0.090, 1.0)]
    )
