"""Ghostmax dampening: a verifiable computation rendered into the paper.

Ghostmax (softmax1, Miller 2023 - praxis/functional/ghostmax.py) divides attention
by $1 + \\sum e^{z}$ instead of $\\sum e^{z}$, an implicit zero-logit ghost that
absorbs probability mass. This module computes the consequence and draws it: the
fraction of attention a head spends on real tokens, as the match strength of the
context varies. Standard softmax always spends one (a forced average); ghostmax
spends $n e^{\\ell}/(1 + n e^{\\ell})$, which falls to zero when nothing matches -
the dampening valve that keeps a harmonic field from fighting forced noise.

The computation is deterministic (no RNG) and self-checking: :func:`_verify`
asserts the plotted curve is the claimed valve before the figure is written, so a
broken claim fails the build rather than rendering a false picture.

Entry point: :func:`export_ghostmax`, driven by :mod:`praxis.pillars.build`.
"""

import os

from praxis.pillars.geometries import FIG_DIR, RESEARCH_DIR

OUT_TEX = os.path.join(RESEARCH_DIR, "ghostmax.tex")
CONTEXT_LEN = 8  # n keys; only the shape matters, not the exact count


def _curves():
    """(match-strength axis, softmax real mass, ghostmax real mass)."""
    import numpy as np

    ell = np.linspace(-8.0, 8.0, 200)  # uniform per-key logit (context match)
    S = CONTEXT_LEN * np.exp(ell)
    ghost = S / (1.0 + S)  # softmax1: real-token mass = S/(1+S)
    soft = np.ones_like(ell)  # softmax always spends its full weight
    return ell, soft, ghost


def _verify() -> dict:
    """Assert the curve is the claimed valve; raise if the claim is false."""
    import numpy as np

    ell, _, ghost = _curves()
    assert np.all((ghost > 0) & (ghost < 1)), "ghostmax real mass must lie in (0,1)"
    assert np.all(np.diff(ghost) > 0), "real mass must rise with match strength"
    assert ghost[0] < 0.01 and ghost[-1] > 0.99, "valve must sweep ~0 -> ~1"
    return {"min_mass": float(ghost.min()), "max_mass": float(ghost.max())}


def render_png() -> str:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    ell, soft, ghost = _curves()
    os.makedirs(FIG_DIR, exist_ok=True)
    fig, ax = plt.subplots(figsize=(4.0, 2.4))
    ax.plot(ell, soft, label="softmax", color="#7a7a7a", lw=2)
    ax.plot(ell, ghost, label="ghostmax (softmax1)", color="#d8541e", lw=2)
    ax.set_xlabel("context match strength (logit per key)")
    ax.set_ylabel("attention on real tokens")
    ax.set_ylim(-0.03, 1.05)
    ax.legend(fontsize=7, frameon=False, loc="center left")
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)
    out = os.path.join(FIG_DIR, "ghostmax.png")
    fig.savefig(out, dpi=120, bbox_inches="tight")
    plt.close(fig)
    return os.path.relpath(out, RESEARCH_DIR)


def figure_tex(path: str) -> str:
    caption = (
        "Ghostmax as a dampening valve. Standard softmax always spends its full "
        "weight on the real tokens (flat at one), so a head emits a "
        "full-magnitude average even when nothing matches. Ghostmax (softmax1,~"
        "\\cite{miller2023}) routes the surplus to a zero-valued ghost, so the "
        "attention spent on real tokens is $n e^{\\ell}/(1 + n e^{\\ell})$ and "
        "falls to zero as the match strength $\\ell$ drops - the head goes quiet "
        "instead of injecting noise the harmonic field would have to cancel."
    )
    return (
        "\\newcommand{\\paperGhostmaxFigure}{%\n"
        "\\begin{figure}[tbp]\n  \\centering\n  "
        f"\\includegraphics[width=0.6\\linewidth]{{{path}}}\n"
        f"  \\caption{{{caption}}}\n  \\label{{fig:ghostmax}}\n"
        "\\end{figure}\n}\n"
    )


def export_ghostmax() -> dict:
    """Verify the dampening claim, render the figure, write ghostmax.tex."""
    summary = _verify()
    path = render_png()
    with open(OUT_TEX, "w") as fh:
        fh.write("% Generated by praxis/pillars/ghostmax.py - do not edit by hand.\n")
        fh.write(figure_tex(path))
    return summary
