"""Paper threads: which theory the LaTeX system argues, and with what.

The generator sprawl had quietly pigeonholed itself to one paper (the Blind
Watchmaker) because the title and prose were welded into research/main.tex.
A thread pulls the theory out into data: each yaml document under
``praxis/pillars/threads/`` is one layout -

- ``title`` / ``subtitle`` - the title block (research/title.tex)
- ``pillars``              - which content generators (build.py STEPS) run
- COMPONENTS keys (abstract, introduction, theory, conclusion, ...) -
  LaTeX prose, written as macros into research/thread.tex and plugged into
  the single unified research/body.tex at its hooks (\\paperThreadAbstract,
  \\paperThreadIntroduction, ...). Migrating another section out of the
  body is a COMPONENTS entry plus a hook - no further code.

There is one master (main.tex) and one body (body.tex); threads reconfigure
them rather than forking them. The long-term direction is to migrate the
body's inline prose into thread components as-data until the body is a
skeleton. ``--title`` selects a thread at runtime, exactly like the other
registries; the Blind Watchmaker layout is the default.
"""

import glob
import os
from dataclasses import dataclass
from typing import Tuple

import yaml

from praxis.pillars.geometries import RESEARCH_DIR

THREADS_DIR = os.path.join(os.path.dirname(__file__), "threads")
TITLE_TEX = os.path.join(RESEARCH_DIR, "title.tex")
THREAD_TEX = os.path.join(RESEARCH_DIR, "thread.tex")

DEFAULT_THREAD = "blind_watchmaker"

# Component key -> the body.tex hook macro it fills. Order = emission order;
# "abstract" is special-cased (wrapped in the abstract environment).
COMPONENTS = {
    "abstract": "paperThreadAbstract",
    "introduction": "paperThreadIntroduction",
    "theory": "paperThreadTheory",
    "conclusion": "paperThreadConclusion",
}


@dataclass(frozen=True)
class Thread:
    key: str
    title: str
    subtitle: str
    pillars: Tuple[str, ...]  # step keys from praxis.pillars.build.STEPS
    components: Tuple[Tuple[str, str], ...] = ()  # (COMPONENTS key, LaTeX prose)

    def component(self, name: str) -> str:
        return dict(self.components).get(name, "")


def _discover() -> dict:
    registry = {}
    for path in sorted(glob.glob(os.path.join(THREADS_DIR, "*.yml"))):
        key = os.path.splitext(os.path.basename(path))[0]
        with open(path) as fh:
            meta = yaml.safe_load(fh) or {}
        registry[key] = Thread(
            key=key,
            title=str(meta.get("title", key)),
            subtitle=str(meta.get("subtitle", "")),
            pillars=tuple(meta.get("pillars", [])),
            components=tuple(
                (name, str(meta[name]).strip())
                for name in COMPONENTS
                if meta.get(name)
            ),
        )
    return registry


THREAD_REGISTRY = _discover()


def resolve_thread(name=None) -> Thread:
    """Map a --title key (or None) to its Thread."""
    key = name or DEFAULT_THREAD
    if isinstance(key, Thread):
        return key
    if key not in THREAD_REGISTRY:
        raise KeyError(f"Unknown thread {key!r}. Known: {sorted(THREAD_REGISTRY)}")
    return THREAD_REGISTRY[key]


def write_thread(thread: Thread) -> dict:
    """Write the selected thread into research/: the title block and the
    component macros body.tex hooks consume."""
    with open(TITLE_TEX, "w") as fh:
        fh.write("% Generated by praxis/pillars/thread.py - do not edit by hand.\n")
        fh.write("\\newcommand{\\paperTitle}{" + thread.title + "}\n")
        fh.write("\\newcommand{\\paperSubtitle}{" + thread.subtitle + "}\n")

    written = []
    with open(THREAD_TEX, "w") as fh:
        fh.write(
            f"% Generated by praxis/pillars/thread.py from threads/{thread.key}.yml "
            "- do not edit by hand.\n"
        )
        for name, prose in thread.components:
            written.append(name)
            if name == "abstract":
                prose = "\\begin{abstract}\n" + prose + "\n\\end{abstract}"
            fh.write(
                "\\newcommand{\\" + COMPONENTS[name] + "}{%\n" + prose + "\n}\n"
            )
    return {"thread": thread.key, "components": written}
